import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import '../../core/constants/app_colors.dart';
import 'widgets/legal_section.dart';

class TermsOfServiceScreen extends StatelessWidget {
  const TermsOfServiceScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return AnnotatedRegion<SystemUiOverlayStyle>(
      value: const SystemUiOverlayStyle(
        statusBarColor: Colors.transparent,
        statusBarIconBrightness: Brightness.dark,
        statusBarBrightness: Brightness.light,
      ),
      child: Scaffold(
        backgroundColor: AppColors.background,
        appBar: AppBar(
          backgroundColor: Colors.transparent,
          surfaceTintColor: Colors.transparent,
          // Style comes from AppBarTheme.titleTextStyle.
          title: const Text('Terms of Service'),
          centerTitle: false,
        ),
        body: const SingleChildScrollView(
          padding: EdgeInsets.all(20),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              LastUpdatedBadge('June 2025'),
              SizedBox(height: 20),
              LegalSection(
                title: '1. Acceptance of Terms',
                body:
                    'By downloading, installing, or using Gowai — AI Travel Planner ("Gowai"), '
                    'you agree to be bound by these Terms of Service ("Terms"). These Terms apply to '
                    'all users of the app.\n\n'
                    'If you do not agree to these Terms, please do not use Gowai.',
              ),
              LegalSection(
                title: '2. Description of Service',
                body:
                    'Gowai is an AI-powered travel planning application that generates personalised '
                    'full-day trip itineraries using Claude AI by Anthropic.\n\n'
                    '⚠️ Important: Itineraries generated by Gowai are AI suggestions only. '
                    'They are not guaranteed to be accurate, complete, or up to date. '
                    'Always verify travel information — including opening hours, entry fees, '
                    'and safety conditions — with official sources before your trip.',
              ),
              LegalSection(
                title: '3. User Accounts',
                body:
                    '• You must provide accurate and complete information when creating your account.\n\n'
                    '• You are solely responsible for maintaining the confidentiality of your account credentials.\n\n'
                    '• You may only maintain one account per person.\n\n'
                    '• You must be 13 years of age or older to use Gowai.\n\n'
                    '• You agree to notify us immediately at gowai.app@gmail.com if you suspect any unauthorised use of your account.',
              ),
              LegalSection(
                title: '4. Free & Pro Plans',
                body: 'Gowai is available on two subscription tiers:\n\n'
                    '• Free Plan — Allows up to 3 AI-generated trips per calendar month at no cost.\n\n'
                    '• Pro Plan — Provides unlimited trip generations and access to premium features '
                    '(offline saving, PDF export, priority AI processing).\n\n'
                    'We reserve the right to modify plan features or limits with reasonable prior notice. '
                    'Existing subscribers will be notified before any changes take effect.',
              ),
              LegalSection(
                title: '5. Acceptable Use',
                body: 'You agree NOT to use Gowai to:\n\n'
                    '• Violate any applicable laws or regulations.\n\n'
                    '• Reverse-engineer, decompile, or disassemble any part of the app.\n\n'
                    '• Share your account credentials with others.\n\n'
                    '• Abuse, overload, or interfere with our AI systems or servers.\n\n'
                    '• Scrape, harvest, or collect data from the app in an automated manner.\n\n'
                    '• Use the app for any commercial purpose without our express written consent.',
              ),
              LegalSection(
                title: '6. AI-Generated Content Disclaimer',
                body:
                    'Trip itineraries provided by Gowai are generated by AI and are suggestions only.\n\n'
                    '• Gowai does not guarantee the accuracy of place names, opening hours, entry fees, distances, or travel times.\n\n'
                    '• AI outputs may contain errors, outdated information, or hallucinated details.\n\n'
                    '• Always verify critical travel information with official tourism websites, local authorities, or the venues themselves.\n\n'
                    '• Gowai and Spotroot Technology LLP are not liable for any travel decisions, losses, accidents, or disappointments resulting from reliance on AI-generated itineraries.',
              ),
              LegalSection(
                title: '7. Intellectual Property',
                body:
                    '• The Gowai application, its design, branding, code, and original content are the intellectual property of Spotroot Technology LLP.\n\n'
                    '• Your trip data — the destinations, preferences, and itineraries you generate — belongs to you.\n\n'
                    '• You grant Gowai a limited, non-exclusive licence to store and process your data solely to provide the service.\n\n'
                    '• You may not copy, reproduce, or distribute any part of Gowai without written permission.',
              ),
              LegalSection(
                title: '8. Termination',
                body:
                    '• We reserve the right to suspend or terminate accounts that violate these Terms, engage in abusive behaviour, or misuse the service.\n\n'
                    '• You may delete your account at any time from Profile → Delete Account. Upon deletion, all your data will be permanently removed.\n\n'
                    '• Termination does not entitle you to a refund of any paid subscription fees.',
              ),
              LegalSection(
                title: '9. Limitation of Liability',
                body:
                    'Gowai is provided on an "as-is" and "as-available" basis without warranties of any kind, either express or implied.\n\n'
                    'To the maximum extent permitted by applicable law, Spotroot Technology LLP shall not be liable for:\n\n'
                    '• Any indirect, incidental, or consequential damages arising from your use of the app.\n\n'
                    '• Any travel-related losses, accidents, missed bookings, or other damages based on AI suggestions.\n\n'
                    '• Service interruptions, data loss, or technical failures beyond our reasonable control.',
              ),
              LegalSection(
                title: '10. Governing Law',
                body:
                    'These Terms of Service are governed by and construed in accordance with the laws of India.\n\n'
                    'Any disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts located in Kerala, India.',
              ),
              LegalSection(
                title: '11. Contact Us',
                body:
                    'If you have any questions about these Terms, please contact us:\n\n'
                    'Spotroot Technology LLP\n'
                    'Email: gowai.app@gmail.com\n'
                    'Website: gowai.app',
              ),
              SizedBox(height: 32),
            ],
          ),
        ),
      ),
    );
  }
}

// Section/badge widgets live in widgets/legal_section.dart (shared with
// the Privacy Policy screen).
